### ISSUE TITLE
Chaudron Screenshots?

### ISSUE THREAD

**Issue by sjb8100** [Green92/Sifteo_bunker#1]
Hi,
I found your Chaudron repo by looking at who was active on sifteo/thundercracker. I am new to sifteo and I am interested to see what can be done with it. Any pictures of the game in current state would help our decision of whether or not to pursue sifteo as a project. Thanks for your time.

**Comment by Lotharioaps** [comment]
Hey,

Here is a link to the description of the project and some pictures.

https://lotharioaps.com/portfolio/cauldron-is-a-game-of-speed-and-memory-for-sifteo-cubes-in-which-the-player-has-to-cook-magical-recipes-to-solve-the-problems-of-the-clients-that-come-into-his-shop/

Although I must warn you that the sifteocubes are no longer in production.

Best regards,

Lothario

**Comment by sjb8100** [comment]
wonderful thank you. I tried to look for a Sifteo "post mortem" as is popular in gaming industry but my first search didn't turn up anything. I understand they open sourced the idea. I suppose hoping for a Phoenix from the ashes from the community. Perhaps a slow growth rather than big launch would work.
